trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    mvn clean test -Dcucumber.options="--tags @UITest"
  displayName: 'execute tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'target/junitreport.xml'
    testRunTitle: 'Test Report'
  displayName: 'Publish Reports'

#- task: PublishCucumberReport@1
#  inputs:
#    jsonDir: './target'
#    outputPath: './target'
#    theme: 'bootstrap'
#    reportSuiteAsScenarios: true
#    name: 'SeleniumwithCucumber'
#    title: 'Selenium with Cucumber'